# Generated by Django 4.2.3 on 2023-07-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(max_length=999, verbose_name='Description')),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
